### ISSUE TITLE
[Crash] Crashing While riding boat / Breaking Lillypad

### ISSUE THREAD

**Issue by TheonlyTazz** [Vyraal1/FTB-Interactions#10]
The Boat and all might be unrelated but still Vyraal1 requested me to post it here:
https://justpaste.it/5pqa8
``` ---- Minecraft Crash Report ----

WARNING: coremods are present:
MalisisSwitchesPlugin (malisisswitches-1.12.2-5.1.0.jar)
Wizardry Plugin (wizardry-0.9.7.jar)
LoadingPlugin (Quark-r1.5-135.jar)
LibrarianLib Plugin (librarianlib-1.12.2-4.15.jar)
EnderCorePlugin (EnderCore-1.12.2-0.5.44.jar)
AdvancedRocketryPlugin (AdvancedRocketry-1.12.2-1.4.1-117-universal.jar)
JEIDLoadingPlugin (JustEnoughIDs-1.0.2-26.jar)
LoadingPlugin (RandomThings-MC1.12.2-4.2.4.jar)
ForgelinPlugin (Forgelin-1.8.2.jar)
CTMCorePlugin (CTM-MC1.12.2-0.3.3.22.jar)
LogisticsPipesCoreLoader (logisticspipes-0.10.1.109.jar)
MalisisCorePlugin (malisiscore-1.12.2-6.4.0.jar)
ShetiPhian-ASM (ShetiPhian-ASM-1.12.0.jar)
BNBGamingCore (BNBGamingCore-1.12.2-0.10.0.jar)
Botania Tweaks Core (botaniatweaks-1.8.2.jar)
Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.3-1.12.2.jar)
LoadingPlugin (ResourceLoader-MC1.12.1-1.5.3.jar)
AppleCore (AppleCore-mc1.12.2-3.1.4.jar)
LoadingPlugin (HardcoreDarkness-MC1.12.2-2.0.jar)
DLFMLCorePlugin (DynamicLights-1.12.2.jar)
AstralCore (astralsorcery-1.12.2-1.10.5.jar)
OpenModsCorePlugin (OpenModsLib-1.12.2-0.12.1.jar)
Inventory Tweaks Coremod (InventoryTweaks-1.64+dev.126.jar)
GottaGoFastLoader (gottagofast-1.1.jar)
Contact their authors BEFORE contacting forge

// Would you like a cupcake?

Time: 12/27/18 11:44 PM
Description: Ticking entity

java.lang.NullPointerException: Ticking entity
at net.minecraft.entity.Entity.func_184191_r(Entity.java:2315)
at net.minecraft.entity.ai.EntityAIHurtByTarget.func_190105_f(SourceFile:57)
at net.minecraft.entity.ai.EntityAIHurtByTarget.func_75249_e(SourceFile:38)
at net.minecraft.entity.ai.EntityAITasks.func_75774_a(SourceFile:102)
at net.minecraft.entity.EntityLiving.func_70626_be(EntityLiving.java:760)
at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:2351)
at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:577)
at net.minecraft.entity.monster.EntityMob.func_70636_d(EntityMob.java:45)
at net.minecraft.entity.monster.EntityZombie.func_70636_d(EntityZombie.java:223)
at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2171)
at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:295)
at net.minecraft.entity.monster.EntityMob.func_70071_h_(EntityMob.java:50)
at net.minecraft.world.World.func_72866_a(World.java:1993)
at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
at net.minecraft.world.World.func_72870_g(World.java:1955)
at net.minecraft.world.World.func_72939_s(World.java:1759)
at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
at java.lang.Thread.run(Thread.java:745)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
at net.minecraft.entity.Entity.func_184191_r(Entity.java:2315)
at net.minecraft.entity.ai.EntityAIHurtByTarget.func_190105_f(SourceFile:57)
at net.minecraft.entity.ai.EntityAIHurtByTarget.func_75249_e(SourceFile:38)
at net.minecraft.entity.ai.EntityAITasks.func_75774_a(SourceFile:102)
at net.minecraft.entity.EntityLiving.func_70626_be(EntityLiving.java:760)
at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:2351)
at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:577)
at net.minecraft.entity.monster.EntityMob.func_70636_d(EntityMob.java:45)
at net.minecraft.entity.monster.EntityZombie.func_70636_d(EntityZombie.java:223)
at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2171)
at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:295)
at net.minecraft.entity.monster.EntityMob.func_70071_h_(EntityMob.java:50)
at net.minecraft.world.World.func_72866_a(World.java:1993)
at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
at net.minecraft.world.World.func_72870_g(World.java:1955)

-- Entity being ticked --
Details:
Entity Type: minecraft:zombie (net.minecraft.entity.monster.EntityZombie)
Entity ID: 105433
Entity Name: Zombie
Entity's Exact location: -1473.50, 66.00, 187.50
Entity's Block location: World: (-1474,66,187), Chunk: (at 14,4,11 in -93,11; contains blocks -1488,0,176 to -1473,255,191), Region: (-3,0; contains chunks -96,0 to -65,31, blocks -1536,0,0 to -1025,255,511)
Entity's Momentum: 0.00, -0.08, 0.00
Entity's Passengers: []
Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
at net.minecraft.world.World.func_72939_s(World.java:1759)
at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)

-- Affected level --
Details:
Level name: New World
All players: 1 total; [EntityPlayerMP['TheonlyTazz'/7, l='New World', x=-1494.93, y=62.07, z=213.40]]
Chunk stats: ServerChunkCache: 627 Drop: 0
Level seed: 8057590091895348385
Level generator: ID 07 - voidworld, ver 0. Features enabled: true
Level generator options: {"coordinateScale":175.0,"heightScale":75.0,"lowerLimitScale":512.0,"upperLimitScale":512.0,"depthNoiseScaleX":200.0,"depthNoiseScaleZ":200.0,"depthNoiseScaleExponent":0.5,"mainNoiseScaleX":165.0,"mainNoiseScaleY":106.61267,"mainNoiseScaleZ":165.0,"baseSize":8.267606,"stretchY":13.387607,"biomeDepthWeight":1.2,"biomeDepthOffset":0.2,"biomeScaleWeight":3.4084506,"biomeScaleOffset":0.0,"seaLevel":63,"useCaves":false,"useDungeons":false,"dungeonChance":7,"useStrongholds":false,"useVillages":true,"useMineShafts":true,"useTemples":true,"useMonuments":true,"useRavines":true,"useWaterLakes":true,"waterLakeChance":49,"useLavaLakes":true,"lavaLakeChance":80,"useLavaOceans":false,"fixedBiome":-1,"biomeSize":4,"riverSize":5,"dirtCount":0,"gravelCount":0,"graniteCount":0,"dioriteCount":0,"andesiteCount":0,"coalCount":0,"ironCount":0,"goldCount":0,"redstoneCount":0,"diamondCount":0,"lapisCount":0}
Level spawn location: World: (-36,72,512), Chunk: (at 12,4,0 in -3,32; contains blocks -48,0,512 to -33,255,527), Region: (-1,1; contains chunks -32,32 to -1,63, blocks -512,0,512 to -1,255,1023)
Level time: 699796 game time, 134232 day time
Level dimension: 100
Level storage version: 0x04ABD - Anvil
Level weather: Rain time: 11147 (now: false), thunder time: 107394 (now: false)
Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
at java.lang.Thread.run(Thread.java:745) ```

**Comment by Saereth** [comment]
this should be fixed with .44 pack release including the new astral update, let me know if it occurs again

**Comment by TeamDman** [comment]
![image](https://user-images.githubusercontent.com/9356891/50536258-7289c000-0b20-11e9-8ba8-ec1a9251bb90.png)
In case anybody was wondering.

**Comment by Saereth** [comment]
this should be fixed now

**Comment by labradoe** [comment]
What mods did this involve? And what version did the fix go in for? I have run into this issue, but the entity being ticked was a Blaze... Google led me here.
